# Generated by Django 5.1.1 on 2024-10-12 00:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_prefecture_travelrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 12, 0, 30, 33, 171794, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prefecture',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.prefecture'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
