# Generated by Django 5.1.1 on 2024-10-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_prefecture_create_at_prefecture_update_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefecture',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='prefecture',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='travelrecord',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='travelrecord',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travelrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
