# Generated by Django 5.1.1 on 2024-10-22 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_photo_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_text', models.TextField(blank=True, null=True)),
                ('memo_photo_path', models.ImageField(blank=True, null=True, upload_to='memo_photos/')),
                ('audio_path', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_transcript', models.TextField(blank=True, null=True)),
                ('memo_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travelrecord')),
            ],
        ),
    ]
