# Generated by Django 5.1.1 on 2024-10-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_travelmemo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelmemo',
            old_name='travel_record_id',
            new_name='travel_record',
        ),
    ]
