# Generated by Django 5.1.1 on 2024-10-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_travel_record_id_travelmemo_travel_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
