# Generated by Django 5.1.1 on 2024-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_travelrecord_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrecord',
            name='main_photo_url',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/'),
        ),
    ]
