# Generated by Django 5.1.1 on 2024-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_travelrecord_main_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
