# Generated by Django 5.1.1 on 2024-11-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_category_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmemo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelmemo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
