# Generated by Django 5.1.1 on 2024-11-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_travelmemo_latitude_travelmemo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelmemo',
            name='audio_path',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
