# Generated by Django 5.1.1 on 2024-11-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_travelmemo_audio_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmemo',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
