# Generated by Django 5.1.1 on 2024-11-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_travelmemo_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelmemo',
            name='audio_file',
        ),
    ]
